- name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'healthfrontend' # Your NEW Blazor web app name
          publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE }} # The NEW secret
          package: ./publish