steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'healthfrontend'
          publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE }}
          package: ./publish